"""Init

Revision ID: 608a6b117580
Revises: de493c31e16e
Create Date: 2025-01-17 13:14:05.114289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608a6b117580'
down_revision: Union[str, None] = 'de493c31e16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fullname', sa.String(length=50), nullable=False))
    op.drop_column('students', 'name')
    op.add_column('teachers', sa.Column('fullname', sa.String(length=50), nullable=False))
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('teachers', 'fullname')
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('students', 'fullname')
    # ### end Alembic commands ###
